DATA = {
    'MOUSE/SMOOTHING': 0.4,
    'MOUSE/ZOOM_SMOOTHING': 0.9,
    'MOUSE/TOUCH_FRIENDLY': False,
    'MOUSE/ZOOM_SENSITIVITY': 0.05,
    'MOUSE/SENSITIVITY': 4.0,
    'MOUSE/Y_INVERT': False,

    'SYS/EXIT_ON_ERROR': True,
    'SYS/LOG_LEVEL': 'DEBUG',
    'SYS/PROFILE': False,

    'KEYS/WEAPON_SELECTION/RESET': 'TABKEY',
    'KEYS/WEAPON_SELECTION/BACK': 'ACCENTGRAVEKEY',
    'KEYS/EMERGENCY_ABORT_KEY': 'ESCKEY'
}


def get(key):
    return DATA[key]
