
MINIGUN_BULLET_CONFIG = {
    "VELOCITY": 853,
    "TRACER_OBJECT": 'MinigunRound',
}

MINIGUN_CONFIG = {
    "YAW_SPEED": 2.0,
    "PITCH_SPEED": 1.0,
    "ROUNDS_PER_MINUTE": 2000,
    "BARREL_ACCELERATION": 8,
    "BARREL_DECELERATION": 5,
    "BARRELS": 6,
    "ROUNDS_PER_TRACER": 3,
    "NUMBER_ROUNDS": 20000,
    "MUZZLE_FLASH_OBJECT": 'MinigunMuzzleFlash',
    "PROJECTILE_CONFIG": MINIGUN_BULLET_CONFIG
}


CAMERA_CONFIG = {
    'MIN_ANGLE': -1.5,
    'MAX_ANGLE': -0.2,
    'MIN_ZOOM_DIST': 50,
    'MIN_ZOOM_FOV': 30,
    'MAX_ZOOM_DIST': 300,
    'MAX_ZOOM_FOV': 110,
}


HERO_CONFIG = {
    'MINIGUN_CONFIG': MINIGUN_CONFIG
}


MAIN_CONFIG = {
    'EXIT_IF_ERROR': True,
    'LOG_LEVEL': 'DEBUG'
}
