
MINIGUN_BULLET_CONFIG = {
    "VELOCITY": 853,
    "TRACER_OBJECT": 'MinigunRound',
    "TRACER_STRETCH_FACTOR": 0.05
}

MINIGUN_CONFIG = {
    "YAW_SPEED": 2.0,
    "PITCH_SPEED": 1.0,
    "ROUNDS_PER_MINUTE": 2000,
    "BARREL_ACCELERATION": 8,
    "BARREL_DECELERATION": 5,
    "BARRELS": 6,
    "ROUNDS_PER_TRACER": 3,
    "NUMBER_ROUNDS": 20000,
    "MUZZLE_FLASH_OBJECT": 'MinigunMuzzleFlash',
    "PROJECTILE_CONFIG": MINIGUN_BULLET_CONFIG
}






RAILGUN_TURRET_BARREL_CONFIG = {
    'MAX_PITCH': 0.87,
    'MIN_PITCH': -0.15,
    'MAX_YAW': 0.05,
    'MIN_YAW': -0.05,
    'PITCH_SPEED': 0.5,
    'YAW_SPEED': 1.0,
    'RECOIL_DISTANCE': 1.0,
    'RECOIL_RECOVER_SPEED': 4.0,
    'FIRE_ANGLE': 0.001
}

RAILGUN_BULLET_CONFIG = {
    "VELOCITY": 2000,
    "TRACER_OBJECT": 'RailgunRound',
    "TRACER_STRETCH_FACTOR": 0.1
}

RAILGUN_CONFIG = {
    'NUMBER_ROUNDS': 1000,
    'RELOAD_TIME': 5.0,
    'SALVO_SEPARATION_TIME':  0.3,
    'YAW_SPEED': 1.0,
    'BARREL_CONFIG': RAILGUN_TURRET_BARREL_CONFIG,
    'MUZZLE_FLASH_OBJECT': 'RailgunMuzzleFlash',
    'PROJECTILE_CONFIG': RAILGUN_BULLET_CONFIG
}

HERO_SHIP_HOVER_THRUSTERS = {
    'HOVER_HEIGHT': 20,
    'THRUST_MULTIPLIER': 10,
}

HERO_CONFIG = {
    'MINIGUN_CONFIG': MINIGUN_CONFIG,
    'RAILGUN_CONFIG': RAILGUN_CONFIG,
    'SPEED_LINEAR': 20,
    'SPEED_TURN': 200,
    'THRUSTER_CONFIG': HERO_SHIP_HOVER_THRUSTERS,
}



HUD_CATEGORY_MINIGUN = {
	'TEXT': 'Minigun',
	'IMAGE_OFFSET': 0
}
HUD_CATEGORY_RAILGUN = {
	'TEXT': 'Railgun',
	'IMAGE_OFFSET': 1/4
}

WEAPON_UI_CONFIG = {
	'MINIGUN': HUD_CATEGORY_MINIGUN,
	'RAILGUN': HUD_CATEGORY_RAILGUN,
}

HUD_CONFIG = {
	'WEAPON_UI_CONFIG': WEAPON_UI_CONFIG
}



CAMERA_CONFIG = {
    'MIN_ANGLE': -1.5,
    'MAX_ANGLE': -0.2,
    'MIN_ZOOM_DIST': 50,
    'MIN_ZOOM_FOV': 30,
    'MAX_ZOOM_DIST': 300,
    'MAX_ZOOM_FOV': 110,
}

MOUSE_CONFIG = {
	'DRAG_THRESHOLD': 0.01
}


MAIN_CONFIG = {
	'HUD_CONFIG': HUD_CONFIG,
	'HERO_CONFIG': HERO_CONFIG,
	'CAMERA_CONFIG': CAMERA_CONFIG,
	'MOUSE_CONFIG': MOUSE_CONFIG
}




BULLET_MANAGER_CONFIG = {
    'BULLET_LIMIT': 600
}


SOUND_EFFECTS_SINGLE = [
    'Minigun.wav',
    'Railgun.wav',
]
